server:
  port: "8080"
  host: "0.0.0.0"

database:
  path: "./data/abyss.db"

llm:
  provider: "openai"
  api_key: "sk-jtZytdAzx2AGhMB82862317445Af4a1c89D97724Ab1213E5"
  api_base: "https://api.vveai.com/v1"
  model: "grok-3"
  temperature: 0.7
  max_tokens: 2000

game:
  default_hp: 100
  default_san: 100
  max_turn_per_scene: 20
  enable_adult_mode: false

